# Schemas for defining the structure of the LLM response and metadata as Pydantic's BaseModel.
# The structure containing the LLM response content and metadata such as tokens used, model name, and finish_reason.

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

CollectionStatus = Literal["complete", "partial", "insufficient"]
"""
How much of a comparison actually came back, measured in *usable answers*.

`insufficient` (not "failed") because the calls may all have succeeded and the
batch still not be a comparison - one answer has nothing to be compared against.
"""

AuditStatus = Literal["clean", "degraded"]
"""
Whether the money ledger for a batch is complete.

`degraded` means something was billed but not fully accounted for. It says nothing
about answer quality, and must never be read as one.
"""

PersistenceStatus = Literal["complete", "partial", "failed"]
"""Whether the audit trail for a batch reached storage. Independent of the two above."""


class TokenUsageInfo(BaseModel):
    """
     Provider-neutral token usage for a single LLM response.

    The field vocabulary is deliberately generic (input/output) so it survives
    adding new providers. Cache-related counts, however, mean different things on
    each provider, so they are kept as separate, explicitly-named fields instead
    of being collapsed into one ambiguous `cached_tokens` value.
    """

    model_config = ConfigDict(extra="forbid")

    input_tokens: int
    """Number of tokens in the prompt."""

    output_tokens: int
    """Number of tokens in the generated completion."""

    total_tokens: int | None = None
    """
    Total tokens for the request, as reported by the provider.

    Optional: some providers (e.g. Anthropic) do not return a total, so the
    service/storage layer may derive it from input + output when it is None.
    """

    # --- Cache accounting (provider-specific semantics, preserved separately) ---
    cached_input_tokens: int | None = None
    """OpenAI: portion of the prompt served from cache (a subset of input_tokens)."""

    cache_creation_input_tokens: int | None = None
    """Anthropic: prompt tokens written to the cache (billed at a premium)."""

    cache_read_input_tokens: int | None = None
    """Anthropic: prompt tokens read from the cache (billed at a discount)."""


class CostInfo(BaseModel):
    """
    Define a Pydantic model to represent the cost information of the LLM's call,
    includiig input, output, and total cost in USD.
    """

    model_config = ConfigDict(extra="forbid")

    input_usd: float
    """The cost of the input token present in the prompt."""

    cached_input_usd: float | None = None
    """The cost of the cached tokens present in the prompt."""

    output_usd: float
    """The cost of the output tokens present in the prompt."""

    total_usd: float
    """The cost of the total tokens used in the request (prompt + completion)."""

    estimated: bool | None = None
    """Indicate estimated cost to avoid confusion when compared to actual billing data."""

    pricing_updated_at: str | None = None
    """Date the token price table was updated. (YYYY-MM-DD)"""

    pricing_source: str | None = None
    """
    Source of token price

    (ex. for OpenAI, refer to [this page](https://developers.openai.com/api/docs/pricing))
    """


class LLMRequest(BaseModel):
    """
    A single, provider-agnostic request to one model.

    This is the only input a provider's `ask()` receives. In multi-compare mode
    the service layer builds one LLMRequest per (provider, model) pair, so the
    response identity travels inside the request rather than being generated by
    the provider.
    """

    model_config = ConfigDict(extra="forbid")

    response_id: str
    """
    UUID identifying the resulting response unit.

    Generated and injected by the service layer (not the provider), so that run
    and response identities are assigned in one place and stay consistent across
    a multi-provider comparison.
    """

    system_prompt: str
    user_question: str
    selected_model: str

    max_tokens: int = 4096
    """
    Upper bound on generated tokens. Required by Anthropic's API; a harmless
    ceiling for providers that cap output differently or ignore it.
    """


class LLMCallResult(BaseModel):
    """
    Define a Pydantic model to represent the result of an LLM's call,
    including the response text, token usage, and other metadata.
    """

    model_config = ConfigDict(extra="forbid")

    response_id: str
    """UUID for identification of individual LLM response units in LLMCallResult"""

    provider: str
    """
    Canonical provider key of the model that generated the response.

    Use the lowercase registry keys ("openai", "anthropic", "google") so the
    value matches what the provider registry and storage layer expect.
    """

    model: str
    """Model used to generate the response."""

    response_text: str
    """Content of the responses provided by the model."""

    finish_reason: str | None = None
    """
    The reason the model stopped generating tokens.

    If the answer has ended normally, it will be marked `stop`.
    """

    raw_response_id: str | None = None
    """Unique ID given to identify the initial response source (Raw Response)."""

    usage: TokenUsageInfo
    """Token usage infomation about the prompt and model's response."""

    cost: CostInfo | None = None
    """Cost information calculated based on token usage."""


class SalvageInfo(BaseModel):
    """
    What could be rescued from a response that was billed but never became a result.

    A post-billing failure other than cost calculation (a parse error, an
    unexpected response shape) leaves no LLMCallResult to preserve, so the run
    would otherwise be logged as a plain failure - indistinguishable from a call
    that never reached the API. This model keeps the fact that money was spent,
    where the pipeline broke, and enough provider-side identity to look the call
    up or reconcile its cost by hand.

    The presence of this object on a log IS the "a response was received" flag.

    The response *body* is deliberately not captured: its location differs per
    provider, and it can carry sensitive prompt content. Only the fields shared
    by the OpenAI-compatible response shapes are read, on a best-effort basis -
    every field below except the first three may be missing.
    """

    model_config = ConfigDict(extra="forbid")

    failed_stage: Literal["parse", "cost", "result_validation"]
    """Which post-billing step failed: response parsing, cost calculation, or result validation."""

    provider: str
    """Canonical provider key of the billed call."""

    requested_model: str
    """Model name that was requested (the response's own model may differ or be unreadable)."""

    raw_type: str | None = None
    """Class name of the raw response object, for diagnosing a changed SDK shape."""

    raw_response_id: str | None = None
    """Provider-side response id, so the billed call stays traceable on their dashboard."""

    raw_model: str | None = None
    """Model name as reported by the response itself, when readable."""

    raw_usage: dict[str, Any] | None = None
    """
    Scalar token-usage fields read straight off the raw response.

    Kept as a loose dict on purpose: normalizing it into TokenUsageInfo is
    exactly the step that just failed. Non-scalar entries are dropped so the
    audit log always stays JSON-serializable.
    """


class CallPolicyInfo(BaseModel):
    """
    The timeout and retry budget a call was made under.

    Recorded so a failure stays interpretable later: "timed out" means something
    different under a 10-second budget than under a 300-second one, and the numbers
    in call_policy.py will change over time while old logs must still be readable.

    This is the *configured* policy for the process (see `resources/call_policy.py`),
    not a measurement - the SDKs do not report how many attempts a call actually
    took, and a provider constructed with a custom client may not follow it.
    """

    model_config = ConfigDict(extra="forbid")

    max_parallel_calls: int
    """Ceiling on simultaneous provider calls in one `compare`."""

    connect_timeout_sec: float
    """Handshake budget; expiring here means nothing was billed."""

    read_timeout_sec: float
    """Response-body budget; expiring here can mean a billed response was lost."""

    max_retries: int
    """Retries the SDK may make after the first attempt. Never applied post-billing."""


class LLMCallLog(BaseModel):
    """
    Define a Pydantic model to represent the log of an LLM's call.
    """

    model_config = ConfigDict(extra="forbid")

    run_id: str
    """UUID for identification of individual LLM response units in LLMCallLog."""

    group_id: str | None = None
    """Shared id tying together the calls of one comparison; None for a single ask."""

    created_at: datetime
    """Timestamp of when the log entry was created."""

    provider: str | None = (
        None  # Which provider was attempted (kept even when the call fails and result is None).
    )
    """Canonical provider key of the model that generated the response."""

    model: str | None = None
    """
    Model that was *requested*.

    Kept next to `provider` so a failed run still records what was attempted - the
    result (which carries the model the provider actually answered with) is None
    on failure, and without this a failed audit row cannot say which model it was.
    """

    system_prompt: str
    """System prompt used for the LLM call."""

    user_prompt: str
    """User prompt used for the LLM call."""

    success: bool
    """Indicates whether the LLM call was successful."""

    error: str | None = None
    """Error message if the LLM call failed."""

    error_type: str | None = (
        None  # Exception class name, so failed calls stay queryable without parsing the message.
    )
    """Type of error that occurred."""

    elapsed_sec: float | None = (
        None  # Latency in seconds, recorded for both successful and failed attempts.
    )
    """Elapsed time for the LLM call in seconds."""

    result: LLMCallResult | None = None
    """The result of the LLM call, if successful."""

    salvage: SalvageInfo | None = None
    """
    Diagnostics for a billed response that never became a result.

    Set only when the paid call went through but a later step failed without
    leaving an LLMCallResult, so a failed run still records that money was spent.
    """

    policy: CallPolicyInfo | None = None
    """Timeout/retry budget in effect for this call; None on logs written before it existed."""


class ErrorInfo(BaseModel):
    """
    A single provider failure represented as data, for the multi-compare flow.

    Design decision (resolved):
      * Provider contracts stay simple — success returns LLMCallResult, failure
        raises (PaidResponseError when a billed response can still be salvaged).
      * Turning a failure into a *value* is the job of the service layer's
        compare loop only: when one provider raises, the others must still
        complete, so each outcome (success or failure) is collected as data and
        a partial/quorum result can be formed.

    Therefore ErrorInfo is produced exclusively by the service/aggregation layer
    (never returned by a provider), keeping provider contracts free of the
    exceptions-vs-data mix.
    """

    model_config = ConfigDict(extra="forbid")

    provider: str
    """Canonical provider key of the failed call ("openai", "anthropic", ...)."""

    model: str | None = None
    """Model that was attempted, when known."""

    error_type: str
    """Exception class name, kept queryable without parsing the message."""

    message: str
    """Human-readable failure description (str of the underlying exception)."""

    elapsed_sec: float | None = None
    """Latency until the failure, recorded for parity with successful calls."""

    partial_result: LLMCallResult | None = None
    """
    A billed-but-failed response promoted to data.

    Carries the LLMCallResult salvaged from a PaidResponseError so a response we
    already paid for is never discarded during aggregation.
    """

    salvage: SalvageInfo | None = None
    """
    Diagnostics for a billed response too broken to yield a partial_result.

    Mirrors LLMCallLog.salvage so aggregation does not drop what the paid call
    left behind when even parsing failed.
    """

    created_at: datetime
    """When the failure was recorded."""


class PersistenceErrorInfo(BaseModel):
    """
    One storage destination refusing an audit log, represented as data.

    Archiving is a *side effect* of a call that may already have been billed, so a
    full disk or a locked database must never take down the result held in memory.
    The write layer therefore reports what it could not store instead of raising,
    and every sink is attempted independently - one entry per sink that failed.
    """

    model_config = ConfigDict(extra="forbid")

    run_id: str
    """The audit log that could not be stored."""

    sink: str
    """Destination that refused it ("jsonl", "sqlite")."""

    error_type: str
    """Exception class name, kept queryable without parsing the message."""

    message: str
    """Human-readable failure description (str of the underlying exception)."""

    written_sinks: list[str] = []
    """
    Destinations that DID accept this log.

    Non-empty next to a failure means the log is now split across stores - the
    JSONL-succeeded-then-SQLite-failed case - so the inconsistency is recorded
    rather than left to be discovered later.
    """

    created_at: datetime
    """When the storage failure was recorded."""
