# Schemas for defining the structure of the LLM response and metadata as Pydantic's BaseModel.
# The structure containing the LLM response content and metadata such as tokens used, model name, and finish_reason.

from datetime import datetime

from pydantic import BaseModel, ConfigDict


class TokenUsageInfo(BaseModel):
    """
     Provider-neutral token usage for a single LLM response.

    The field vocabulary is deliberately generic (input/output) so it survives
    adding new providers. Cache-related counts, however, mean different things on
    each provider, so they are kept as separate, explicitly-named fields instead
    of being collapsed into one ambiguous `cached_tokens` value.
    """

    model_config = ConfigDict(extra="forbid")

    input_tokens: int
    """Number of tokens in the prompt."""

    output_tokens: int
    """Number of tokens in the generated completion."""

    total_tokens: int | None = None
    """
    Total tokens for the request, as reported by the provider.

    Optional: some providers (e.g. Anthropic) do not return a total, so the
    service/storage layer may derive it from input + output when it is None.
    """

    # --- Cache accounting (provider-specific semantics, preserved separately) ---
    cached_input_tokens: int | None = None
    """OpenAI: portion of the prompt served from cache (a subset of input_tokens)."""

    cache_creation_input_tokens: int | None = None
    """Anthropic: prompt tokens written to the cache (billed at a premium)."""

    cache_read_input_tokens: int | None = None
    """Anthropic: prompt tokens read from the cache (billed at a discount)."""


class CostInfo(BaseModel):
    """
    Define a Pydantic model to represent the cost information of the LLM's call,
    includiig input, output, and total cost in USD.
    """

    model_config = ConfigDict(extra="forbid")

    input_usd: float
    """The cost of the input token present in the prompt."""

    cached_input_usd: float | None = None
    """The cost of the cached tokens present in the prompt."""

    output_usd: float
    """The cost of the output tokens present in the prompt."""

    total_usd: float
    """The cost of the total tokens used in the request (prompt + completion)."""

    estimated: bool | None = None
    """Indicate estimated cost to avoid confusion when compared to actual billing data."""

    pricing_updated_at: str | None = None
    """Date the token price table was updated. (YYYY-MM-DD)"""

    pricing_source: str | None = None
    """
    Source of token price

    (ex. for OpenAI, refer to [this page](https://developers.openai.com/api/docs/pricing))
    """


class LLMRequest(BaseModel):
    """
    A single, provider-agnostic request to one model.

    This is the only input a provider's `ask()` receives. In multi-compare mode
    the service layer builds one LLMRequest per (provider, model) pair, so the
    response identity travels inside the request rather than being generated by
    the provider.
    """

    model_config = ConfigDict(extra="forbid")

    response_id: str
    """
    UUID identifying the resulting response unit.

    Generated and injected by the service layer (not the provider), so that run
    and response identities are assigned in one place and stay consistent across
    a multi-provider comparison.
    """

    system_prompt: str
    user_question: str
    selected_model: str

    max_tokens: int = 4096
    """
    Upper bound on generated tokens. Required by Anthropic's API; a harmless
    ceiling for providers that cap output differently or ignore it.
    """


class LLMCallResult(BaseModel):
    """
    Define a Pydantic model to represent the result of an LLM's call,
    including the response text, token usage, and other metadata.
    """

    model_config = ConfigDict(extra="forbid")

    response_id: str
    """UUID for identification of individual LLM response units in LLMCallResult"""

    provider: str
    """
    Canonical provider key of the model that generated the response.

    Use the lowercase registry keys ("openai", "anthropic", "google") so the
    value matches what the provider registry and storage layer expect.
    """

    model: str
    """Model used to generate the response."""

    response_text: str
    """Content of the responses provided by the model."""

    finish_reason: str | None = None
    """
    The reason the model stopped generating tokens.

    If the answer has ended normally, it will be marked `stop`.
    """

    raw_response_id: str | None = None
    """Unique ID given to identify the initial response source (Raw Response)."""

    usage: TokenUsageInfo
    """Token usage infomation about the prompt and model's response."""

    cost: CostInfo | None = None
    """Cost information calculated based on token usage."""


class LLMCallLog(BaseModel):
    """
    Define a Pydantic model to represent the log of an LLM's call.
    """

    model_config = ConfigDict(extra="forbid")

    run_id: str
    """UUID for identification of individual LLM response units in LLMCallLog."""

    group_id: str | None = None
    """Shared id tying together the calls of one comparison; None for a single ask."""

    created_at: datetime
    """Timestamp of when the log entry was created."""

    provider: str | None = (
        None  # Which provider was attempted (kept even when the call fails and result is None).
    )
    """Canonical provider key of the model that generated the response."""

    system_prompt: str
    """System prompt used for the LLM call."""

    user_prompt: str
    """User prompt used for the LLM call."""

    success: bool
    """Indicates whether the LLM call was successful."""

    error: str | None = None
    """Error message if the LLM call failed."""

    error_type: str | None = (
        None  # Exception class name, so failed calls stay queryable without parsing the message.
    )
    """Type of error that occurred."""

    elapsed_sec: float | None = (
        None  # Latency in seconds, recorded for both successful and failed attempts.
    )
    """Elapsed time for the LLM call in seconds."""

    result: LLMCallResult | None = None
    """The result of the LLM call, if successful."""


class ErrorInfo(BaseModel):
    """
    A single provider failure represented as data, for the multi-compare flow.

    Design decision (resolved):
      * Provider contracts stay simple — success returns LLMCallResult, failure
        raises (PaidResponseError when a billed response can still be salvaged).
      * Turning a failure into a *value* is the job of the service layer's
        compare loop only: when one provider raises, the others must still
        complete, so each outcome (success or failure) is collected as data and
        a partial/quorum result can be formed.

    Therefore ErrorInfo is produced exclusively by the service/aggregation layer
    (never returned by a provider), keeping provider contracts free of the
    exceptions-vs-data mix.
    """

    model_config = ConfigDict(extra="forbid")

    provider: str
    """Canonical provider key of the failed call ("openai", "anthropic", ...)."""

    model: str | None = None
    """Model that was attempted, when known."""

    error_type: str
    """Exception class name, kept queryable without parsing the message."""

    message: str
    """Human-readable failure description (str of the underlying exception)."""

    elapsed_sec: float | None = None
    """Latency until the failure, recorded for parity with successful calls."""

    partial_result: LLMCallResult | None = None
    """
    A billed-but-failed response promoted to data.

    Carries the LLMCallResult salvaged from a PaidResponseError so a response we
    already paid for is never discarded during aggregation.
    """

    created_at: datetime
    """When the failure was recorded."""
